Double xmobar config working and pleasing. Updates to build scripts

diff --git a/build b/build
--- a/build
+++ b/build
@@ -6,27 +6,14 @@ SRC="$HOME/.xmobar"
 # installation directory
 DST="$HOME/bin"
 
-# real path of installed xmobar
-XMB=$(realpath "$(which xmobar)")
-
-# ghc version
-GHC="9.2.8"
-
 # cabal version
 # CBL="3.8.1.0"
 CBL="3.6.2.0"
 
-# name of cached build binary
-OUT="$SRC/xmobar-$(uname -m)-linux"
-
-# error code
+# set the return code
 ERR=0
 
-if test "$#" -gt 1; then
-  ERR=1
-  >&2 echo "ERROR: too many arguments"
-  exit "$ERR"
-fi
+# test existence of source and dst
 
 if ! test -d "$SRC"; then
   ERR=1
@@ -40,38 +27,14 @@ if ! test -d "$DST"; then
   exit "$ERR"
 fi
 
-if test "$#" -eq 1; then
-  OUT="$1"
-fi
-
 cd "$SRC"
 
-# if test -z "$XMB" || test "$SRC/Main.hs" -nt "$XMB"; then
-ghcup -c run --ghc "$GHC" --cabal "$CBL" -- cabal install config \
+# install binary to $DST wtih cabal version $CBL
+ghcup -c run --cabal "$CBL" -- cabal install config \
   --enable-executable-stripping \
   --enable-optimization=2 \
   --overwrite-polic=always \
   --installdir="$DST"
-ERR=$?
-# fi
 
-if test "$ERR" -ne 0; then
-  >&2 echo "ERROR: build failure"
-  exit "$ERR"
-fi
-
-ln -sf "$DST/xmobar" "$SRC/xmobar"
-if test "$?" -ne 0; then
-  ERR="$?"
-  >&2 echo "ERROR: link failure"
-  exit "$ERR"
-fi
-
-ln -sf "$SRC/xmobar" "$OUT"
-if test "$?" -ne 0; then
-  ERR="$?"
-  >&2 echo "ERROR: link failure"
-  exit "$ERR"
-fi
-
-exit "$ERR"
+# exit with error code of last command
+exit "$?"
